#!/usr/bin/env bash
# Reading /etc/passwd line-by-line using IFS=':' and a while loop

while IFS=':' read -r USERNAME PASSWORD USERID GROUPID INFO HOME SHELL
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" \
    "$USERNAME" "$GROUPID" "$HOME" "$SHELL" "$USERID" "$PASSWORD" "$INFO"
done < /etc/passwd


